import { Promotion } from "@/types";

export interface PromotionExtraOption {
  id: string;
  name: string;
  pricePkr: number;
  category: "crust" | "dip" | "beverage" | "side";
}

export const PROMOTION_EXTRAS: PromotionExtraOption[] = [
  { id: "extra_stuffed_crust", name: "Cheese Stuffed Crust", pricePkr: 350, category: "crust" },
  { id: "extra_mozzarella", name: "Extra Mozzarella Cheese", pricePkr: 200, category: "crust" },
  { id: "extra_garlic_mayo", name: "Garlic Mayo Dip", pricePkr: 70, category: "dip" },
  { id: "extra_chipotle_mayo", name: "Chipotle Mayo Dip", pricePkr: 70, category: "dip" },
  { id: "extra_ranch_dip", name: "Ranch Dip", pricePkr: 70, category: "dip" },
  { id: "extra_soft_drink_345", name: "Chilled Soft Drink (345ml)", pricePkr: 120, category: "beverage" },
];

export const PRESET_KITCHEN_NOTES = [
  "Extra Spicy 🌶️",
  "Mild / Less Spicy",
  "Extra Crispy Crust",
  "Sauce on the Side",
  "No Onions",
  "Well Done",
];

export const COMPLETE_PROMOTIONS_DATA: Promotion[] = [
  {
    id: "promo_pizza_treat",
    slug: "pizza-treat",
    title: "Pizza Treat Feast",
    shortDescription: "Tray Pizza + 6 Pcs Oven Baked Wings + Regular Fries with Dip + 1.5L Soft Drink",
    imageUrl: "https://res.cloudinary.com/duo55lhwh/image/upload/c_limit,w_1200,f_auto,q_auto/promotion_1_fthixm",
    cloudinaryPublicId: "promotion_1_fthixm",
    displayOrder: 1,
    isActive: true,
    promotionType: "bundle",
    fixedPricePkr: 2999,
    badgeText: "FEAST 2999",
    termsText: "Includes 1 Large Tray Pizza, 6 Oven Baked Wings, 1 Regular Fries with Dip, and 1.5L Drink.",
    rules: [
      {
        id: "p1_rule_tray_pizza",
        promotionId: "promo_pizza_treat",
        ruleType: "product_choice",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Choose Tray Pizza Flavor",
        displayOrder: 1,
        options: [
          { id: "p1_rule_tray_pizza_opt_0", promotionRuleId: "p1_rule_tray_pizza", productId: "prod_flaming_tikka_pizza", optionTitle: "Flaming Tikka Tray Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
          { id: "p1_rule_tray_pizza_opt_1", promotionRuleId: "p1_rule_tray_pizza", productId: "prod_behari_kebab_pizza", optionTitle: "Behari Kebab Tray Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 2, isAvailable: true },
          { id: "p1_rule_tray_pizza_opt_2", promotionRuleId: "p1_rule_tray_pizza", productId: "prod_hot_pepperoni_pizza", optionTitle: "Hot Pepperoni Tray Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 3, isAvailable: true },
          { id: "p1_rule_tray_pizza_opt_3", promotionRuleId: "p1_rule_tray_pizza", productId: "prod_creamy_alfredo_pizza", optionTitle: "Creamy Alfredo Tray Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 4, isAvailable: true },
          { id: "p1_rule_tray_pizza_opt_4", promotionRuleId: "p1_rule_tray_pizza", productId: "prod_secret_cnm_pizza", optionTitle: "Secret CNM Tray Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 5, isAvailable: true },
          { id: "p1_rule_tray_pizza_opt_5", promotionRuleId: "p1_rule_tray_pizza", productId: "prod_chicken_tikka_pizza", optionTitle: "Chicken Tikka Supreme Tray Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 6, isAvailable: true },
          { id: "p1_rule_tray_pizza_opt_6", promotionRuleId: "p1_rule_tray_pizza", productId: "prod_fajita_sicilian_pizza", optionTitle: "Chicken Fajita Sicilian Tray Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 7, isAvailable: true },
        ],
      },
      {
        id: "p1_rule_baked_wings",
        promotionId: "promo_pizza_treat",
        ruleType: "fixed_item",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Included: Oven Baked Wings (6 Pcs)",
        displayOrder: 2,
        options: [
          { id: "p1_rule_baked_wings_opt_0", promotionRuleId: "p1_rule_baked_wings", productId: "prod_oven_baked_wings", productVariantId: "var_prod_oven_baked_wings_6_pcs_oven_baked_wings", optionTitle: "6 Pcs Oven Baked Wings", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
        ],
      },
      {
        id: "p1_rule_fries",
        promotionId: "promo_pizza_treat",
        ruleType: "fixed_item",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Included: Regular Fries with Dip",
        displayOrder: 3,
        options: [
          { id: "p1_rule_fries_opt_0", promotionRuleId: "p1_rule_fries", productId: "prod_regular_fries", optionTitle: "Regular Fries with Dip", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
        ],
      },
      {
        id: "p1_rule_drink",
        promotionId: "promo_pizza_treat",
        ruleType: "product_choice",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Choose 1.5L Soft Drink",
        displayOrder: 4,
        options: [
          { id: "p1_rule_drink_opt_0", promotionRuleId: "p1_rule_drink", productId: "prod_soda_woda", productVariantId: "var_prod_soda_woda_large_bottle_1_5l_", optionTitle: "Coca-Cola (1.5L)", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
          { id: "p1_rule_drink_opt_1", promotionRuleId: "p1_rule_drink", productId: "prod_soda_woda", productVariantId: "var_prod_soda_woda_large_bottle_1_5l_", optionTitle: "Sprite (1.5L)", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 2, isAvailable: true },
          { id: "p1_rule_drink_opt_2", promotionRuleId: "p1_rule_drink", productId: "prod_soda_woda", productVariantId: "var_prod_soda_woda_large_bottle_1_5l_", optionTitle: "Fanta (1.5L)", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 3, isAvailable: true },
        ],
      },
    ],
  },
  {
    id: "promo_wallet_deal",
    slug: "wallet-deal",
    title: "Your Wallet Loves This Deal",
    shortDescription: "Deal 1: 1 Medium Pizza & 1 Litre Soft Drink for Rs. 1290 | Deal 2: 1 Large Pizza & 1 Litre Soft Drink for Rs. 1850",
    imageUrl: "https://res.cloudinary.com/duo55lhwh/image/upload/c_limit,w_1200,f_auto,q_auto/promotion_2_ofnzlq",
    cloudinaryPublicId: "promotion_2_ofnzlq",
    displayOrder: 2,
    isActive: true,
    promotionType: "tiered",
    fixedPricePkr: 1290,
    badgeText: "FROM 1290",
    termsText: "Choose between Deal 1 (Medium + Drink) or Deal 2 (Large + Drink).",
    rules: [
      {
        id: "p2_rule_tier",
        promotionId: "promo_wallet_deal",
        ruleType: "tier_choice",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Choose Deal Tier",
        displayOrder: 1,
        options: [
          { id: "p2_rule_tier_opt_med", promotionRuleId: "p2_rule_tier", optionTitle: "Deal 1: 1 Medium Pizza & 1 Ltr Drink (Rs. 1,290)", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
          { id: "p2_rule_tier_opt_large", promotionRuleId: "p2_rule_tier", optionTitle: "Deal 2: 1 Large Pizza & 1 Ltr Drink (Rs. 1,850)", quantity: 1, priceAdjustmentPkr: 560, displayOrder: 2, isAvailable: true },
        ],
      },
      {
        id: "p2_rule_flavor",
        promotionId: "promo_wallet_deal",
        ruleType: "product_choice",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Choose Pizza Flavor",
        displayOrder: 2,
        options: [
          { id: "p2_rule_flavor_opt_0", promotionRuleId: "p2_rule_flavor", productId: "prod_flaming_tikka_pizza", optionTitle: "Flaming Tikka Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
          { id: "p2_rule_flavor_opt_1", promotionRuleId: "p2_rule_flavor", productId: "prod_behari_kebab_pizza", optionTitle: "Behari Kebab Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 2, isAvailable: true },
          { id: "p2_rule_flavor_opt_2", promotionRuleId: "p2_rule_flavor", productId: "prod_hot_pepperoni_pizza", optionTitle: "Hot Pepperoni Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 3, isAvailable: true },
          { id: "p2_rule_flavor_opt_3", promotionRuleId: "p2_rule_flavor", productId: "prod_creamy_alfredo_pizza", optionTitle: "Creamy Alfredo Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 4, isAvailable: true },
          { id: "p2_rule_flavor_opt_4", promotionRuleId: "p2_rule_flavor", productId: "prod_secret_cnm_pizza", optionTitle: "Secret CNM Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 5, isAvailable: true },
          { id: "p2_rule_flavor_opt_5", promotionRuleId: "p2_rule_flavor", productId: "prod_chicken_tikka_pizza", optionTitle: "Chicken Tikka Supreme Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 6, isAvailable: true },
          { id: "p2_rule_flavor_opt_6", promotionRuleId: "p2_rule_flavor", productId: "prod_fajita_sicilian_pizza", optionTitle: "Chicken Fajita Sicilian Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 7, isAvailable: true },
          { id: "p2_rule_flavor_opt_7", promotionRuleId: "p2_rule_flavor", productId: "prod_cheese_lover_pizza", optionTitle: "Four-Cheese Lover Pizza", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 8, isAvailable: true },
        ],
      },
      {
        id: "p2_rule_drink",
        promotionId: "promo_wallet_deal",
        ruleType: "product_choice",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Choose 1 Liter Drink",
        displayOrder: 3,
        options: [
          { id: "p2_rule_drink_opt_0", promotionRuleId: "p2_rule_drink", productId: "prod_soda_woda", optionTitle: "Pepsi (1 Liter)", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
          { id: "p2_rule_drink_opt_1", promotionRuleId: "p2_rule_drink", productId: "prod_soda_woda", optionTitle: "7Up (1 Liter)", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 2, isAvailable: true },
          { id: "p2_rule_drink_opt_2", promotionRuleId: "p2_rule_drink", productId: "prod_soda_woda", optionTitle: "Mirinda (1 Liter)", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 3, isAvailable: true },
        ],
      },
    ],
  },
  {
    id: "promo_cheesier_launch",
    slug: "cheesier-medium-pizza-launch",
    title: "1 Medium Pizza Launch Offer",
    shortDescription: "Oops! Things Just Got Cheesier! Get 1 freshly baked Medium Pizza for only Rs. 990.",
    imageUrl: "https://res.cloudinary.com/duo55lhwh/image/upload/c_limit,w_1200,f_auto,q_auto/promotion_3_pkzoe9",
    cloudinaryPublicId: "promotion_3_pkzoe9",
    displayOrder: 3,
    isActive: true,
    promotionType: "single",
    fixedPricePkr: 990,
    badgeText: "LAUNCH Rs. 990",
    termsText: "Exclusive Launch Offer valid for Medium (10 inch) Pizza only. Small and Large sizes not applicable.",
    rules: [
      {
        id: "p3_rule_medium_pizza",
        promotionId: "promo_cheesier_launch",
        ruleType: "product_choice",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Choose Medium (10 inch) Pizza Flavor",
        displayOrder: 1,
        options: [
          { id: "p3_rule_medium_pizza_opt_0", promotionRuleId: "p3_rule_medium_pizza", productId: "prod_flaming_tikka_pizza", productVariantId: "var_prod_flaming_tikka_pizza_medium_10_inch_", optionTitle: "Flaming Tikka (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
          { id: "p3_rule_medium_pizza_opt_1", promotionRuleId: "p3_rule_medium_pizza", productId: "prod_behari_kebab_pizza", productVariantId: "var_prod_behari_kebab_pizza_medium_10_inch_", optionTitle: "Behari Kebab (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 2, isAvailable: true },
          { id: "p3_rule_medium_pizza_opt_2", promotionRuleId: "p3_rule_medium_pizza", productId: "prod_hot_pepperoni_pizza", productVariantId: "var_prod_hot_pepperoni_pizza_medium_10_inch_", optionTitle: "Hot Pepperoni (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 3, isAvailable: true },
          { id: "p3_rule_medium_pizza_opt_3", promotionRuleId: "p3_rule_medium_pizza", productId: "prod_creamy_alfredo_pizza", productVariantId: "var_prod_creamy_alfredo_pizza_medium_10_inch_", optionTitle: "Creamy Alfredo (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 4, isAvailable: true },
          { id: "p3_rule_medium_pizza_opt_4", promotionRuleId: "p3_rule_medium_pizza", productId: "prod_secret_cnm_pizza", productVariantId: "var_prod_secret_cnm_pizza_medium_10_inch_", optionTitle: "Secret CNM (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 5, isAvailable: true },
          { id: "p3_rule_medium_pizza_opt_5", promotionRuleId: "p3_rule_medium_pizza", productId: "prod_chicken_tikka_pizza", productVariantId: "var_tikka_med", optionTitle: "Chicken Tikka Supreme (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 6, isAvailable: true },
          { id: "p3_rule_medium_pizza_opt_6", promotionRuleId: "p3_rule_medium_pizza", productId: "prod_fajita_sicilian_pizza", productVariantId: "var_fajita_med", optionTitle: "Chicken Fajita Sicilian (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 7, isAvailable: true },
          { id: "p3_rule_medium_pizza_opt_7", promotionRuleId: "p3_rule_medium_pizza", productId: "prod_cheese_lover_pizza", productVariantId: "var_cheese_med", optionTitle: "Cheesy Four-Cheese Lover (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 8, isAvailable: true },
        ],
      },
    ],
  },
  {
    id: "promo_bogo_pizza",
    slug: "bogo-pizza-deal",
    title: "Buy 1 Get 1 Pizza Free",
    shortDescription: "Oops! Buy 1 Get 1 Pizza Free for Rs. 1499. Choose any 2 delicious pizzas!",
    imageUrl: "https://res.cloudinary.com/duo55lhwh/image/upload/c_limit,w_1200,f_auto,q_auto/promotion_4_z7vq6y",
    cloudinaryPublicId: "promotion_4_z7vq6y",
    displayOrder: 4,
    isActive: true,
    promotionType: "bundle",
    fixedPricePkr: 1499,
    badgeText: "BOGO 1499",
    termsText: "Buy 1 Get 1 Pizza Free for Rs. 1499. Valid for dine-in, takeaway, and delivery.",
    rules: [
      {
        id: "p4_rule_pizza_1",
        promotionId: "promo_bogo_pizza",
        ruleType: "product_choice",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Choose 1st Pizza Flavor",
        displayOrder: 1,
        options: [
          { id: "p4_rule_pizza_1_opt_0", promotionRuleId: "p4_rule_pizza_1", productId: "prod_flaming_tikka_pizza", productVariantId: "var_prod_flaming_tikka_pizza_medium_10_inch_", optionTitle: "Flaming Tikka (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
          { id: "p4_rule_pizza_1_opt_1", promotionRuleId: "p4_rule_pizza_1", productId: "prod_behari_kebab_pizza", productVariantId: "var_prod_behari_kebab_pizza_medium_10_inch_", optionTitle: "Behari Kebab (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 2, isAvailable: true },
          { id: "p4_rule_pizza_1_opt_2", promotionRuleId: "p4_rule_pizza_1", productId: "prod_hot_pepperoni_pizza", productVariantId: "var_prod_hot_pepperoni_pizza_medium_10_inch_", optionTitle: "Hot Pepperoni (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 3, isAvailable: true },
          { id: "p4_rule_pizza_1_opt_3", promotionRuleId: "p4_rule_pizza_1", productId: "prod_creamy_alfredo_pizza", productVariantId: "var_prod_creamy_alfredo_pizza_medium_10_inch_", optionTitle: "Creamy Alfredo (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 4, isAvailable: true },
          { id: "p4_rule_pizza_1_opt_4", promotionRuleId: "p4_rule_pizza_1", productId: "prod_secret_cnm_pizza", productVariantId: "var_prod_secret_cnm_pizza_medium_10_inch_", optionTitle: "Secret CNM (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 5, isAvailable: true },
          { id: "p4_rule_pizza_1_opt_5", promotionRuleId: "p4_rule_pizza_1", productId: "prod_chicken_tikka_pizza", productVariantId: "var_tikka_med", optionTitle: "Chicken Tikka Supreme (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 6, isAvailable: true },
          { id: "p4_rule_pizza_1_opt_6", promotionRuleId: "p4_rule_pizza_1", productId: "prod_fajita_sicilian_pizza", productVariantId: "var_fajita_med", optionTitle: "Chicken Fajita Sicilian (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 7, isAvailable: true },
          { id: "p4_rule_pizza_1_opt_7", promotionRuleId: "p4_rule_pizza_1", productId: "prod_cheese_lover_pizza", productVariantId: "var_cheese_med", optionTitle: "Cheesy Four-Cheese Lover (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 8, isAvailable: true },
        ],
      },
      {
        id: "p4_rule_pizza_2",
        promotionId: "promo_bogo_pizza",
        ruleType: "product_choice",
        minSelections: 1,
        maxSelections: 1,
        required: true,
        ruleLabel: "Choose 2nd (Free) Pizza Flavor",
        displayOrder: 2,
        options: [
          { id: "p4_rule_pizza_2_opt_0", promotionRuleId: "p4_rule_pizza_2", productId: "prod_flaming_tikka_pizza", productVariantId: "var_prod_flaming_tikka_pizza_medium_10_inch_", optionTitle: "Flaming Tikka (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 1, isAvailable: true },
          { id: "p4_rule_pizza_2_opt_1", promotionRuleId: "p4_rule_pizza_2", productId: "prod_behari_kebab_pizza", productVariantId: "var_prod_behari_kebab_pizza_medium_10_inch_", optionTitle: "Behari Kebab (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 2, isAvailable: true },
          { id: "p4_rule_pizza_2_opt_2", promotionRuleId: "p4_rule_pizza_2", productId: "prod_hot_pepperoni_pizza", productVariantId: "var_prod_hot_pepperoni_pizza_medium_10_inch_", optionTitle: "Hot Pepperoni (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 3, isAvailable: true },
          { id: "p4_rule_pizza_2_opt_3", promotionRuleId: "p4_rule_pizza_2", productId: "prod_creamy_alfredo_pizza", productVariantId: "var_prod_creamy_alfredo_pizza_medium_10_inch_", optionTitle: "Creamy Alfredo (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 4, isAvailable: true },
          { id: "p4_rule_pizza_2_opt_4", promotionRuleId: "p4_rule_pizza_2", productId: "prod_secret_cnm_pizza", productVariantId: "var_prod_secret_cnm_pizza_medium_10_inch_", optionTitle: "Secret CNM (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 5, isAvailable: true },
          { id: "p4_rule_pizza_2_opt_5", promotionRuleId: "p4_rule_pizza_2", productId: "prod_chicken_tikka_pizza", productVariantId: "var_tikka_med", optionTitle: "Chicken Tikka Supreme (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 6, isAvailable: true },
          { id: "p4_rule_pizza_2_opt_6", promotionRuleId: "p4_rule_pizza_2", productId: "prod_fajita_sicilian_pizza", productVariantId: "var_fajita_med", optionTitle: "Chicken Fajita Sicilian (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 7, isAvailable: true },
          { id: "p4_rule_pizza_2_opt_7", promotionRuleId: "p4_rule_pizza_2", productId: "prod_cheese_lover_pizza", productVariantId: "var_cheese_med", optionTitle: "Cheesy Four-Cheese Lover (Medium 10\")", quantity: 1, priceAdjustmentPkr: 0, displayOrder: 8, isAvailable: true },
        ],
      },
    ],
  },
];
